name: multisig_helper
description: A Peercoin multisig helper bot.
version: 1.1.0
repository: https://github.com/peerchemist/multisig_helper_bot/

environment:
  sdk: ^3.2.0
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
dependencies:
  coinlib: ^4.1.0
  dio: ^5.9.1
  televerse: ^2.0.1
